AWSTemplateFormatVersion: '2010-09-09'
Description: 'api-gateway-to-sagemaker-connection

  SAM - Sentiment analyis

  '
Globals:
  Function:
    Timeout: 3
Resources:
  SentimentAnalysisFunction:
    Properties:
      CodeUri: s3://acme-development-lamdba-functions/sam/sentiment-analysis/master-0-gd91aab6/2acef49c2c786fe420c296ce06ff8a1f
      Events:
        HelloWorld:
          Properties:
            Method: post
            Path: /sentiment
          Type: Api
      Handler: sentiment_analysis_func.lambda_handler
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - sagemaker:InvokeEndpoint
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
