AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-gateway-to-sagemaker-connection

  SAM - Sentiment analyis


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SentimentAnalysisFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: sentiment_analysis_func.lambda_handler
      Runtime: python3.6
      #Role: !GetAtt 'LambdaExecutionRole.Arn'
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - sagemaker:InvokeEndpoint
              Resource: '*'
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sentiment
            Method: post

#
#  LambdaExecutionRole:
#    Type: "AWS::IAM::Role"
#    Properties:
#      RoleName: lambda-execution-role
#      AssumeRolePolicyDocument:
#        Statement:
#          - Effect: "Allow"
#            Principal:
#              Service:
#                - "sagemaker.amazonaws.com"
#            Action:
#              - "sts:AssumeRole"
#      ManagedPolicyArns:
#        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"


