AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Sagemaker Stack for sentiment-analyis


Resources:
  SentimentAnalysisCodeRepository:
    Type: AWS::SageMaker::CodeRepository
    Properties:
      CodeRepositoryName: sagemaker-deployment-repository
      GitConfig:
        Branch: master
        RepositoryUrl: https://github.com/petersiemen/sagemaker-deployment

  SageMakerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
      Path: "/service-role/"
      Policies:
        - PolicyName: SageMakerS3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - 'arn:aws:s3:::sagemaker-eu-central-1-982023434191'
                  - 'arn:aws:s3:::sagemaker-eu-central-1-982023434191/*'


  SentimentAnalyisNotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      DefaultCodeRepository: sagemaker-deployment-repository

      #  Notebook Instances Are Internet-Enabled by Default.
      # If you set this to Disabled this notebook instance will be able to access resources only in your VPC,
      # and will not be able to connect to Amazon SageMaker training and endpoint services unless your configure a NAT Gateway in your VPC.
      DirectInternetAccess: Enabled
      InstanceType: ml.t3.medium
      NotebookInstanceName: sentiment-analyis-rnn
      RoleArn: !GetAtt 'SageMakerExecutionRole.Arn'
      RootAccess: Enabled
      VolumeSizeInGB: 5

